"""initial

Revision ID: 3809b2c1a75d
Revises: 
Create Date: 2023-03-30 18:15:45.841881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3809b2c1a75d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('address', sa.String(length=70), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('priv_key', sa.String(length=328), nullable=False),
    sa.PrimaryKeyConstraint('address'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('txid', sa.String(length=80), nullable=False),
    sa.Column('vout', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('is_cb_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('address', sa.String(length=70), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('forward_txid', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['address'], ['addresses.address'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txid', 'address')
    )
    op.create_index(op.f('ix_payments_address'), 'payments', ['address'], unique=False)
    op.create_index(op.f('ix_payments_is_cb_active'), 'payments', ['is_cb_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_is_cb_active'), table_name='payments')
    op.drop_index(op.f('ix_payments_address'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('addresses')
    # ### end Alembic commands ###
